mqtt:
        client:
                protocol: 4
        connection:
                host: 192.168.1.22
                port: 1883
                keepalive: 60
        private_path: robot
       
bridge:
          #Voltage Data Communication
        - factory: mqtt_bridge.bridge:RosToMqttBridge
          msg_type: std_msgs.msg:Float32
          topic_from: /voltage
          topic_to: ~/voltageToMqtt
          
          #Twist Communication
        - factory: mqtt_bridge.bridge:RosToMqttBridge
          msg_type: geometry_msgs.msg:Twist 
          topic_from: /cmd_vel
          topic_to: ~/fromCmdVel
        
          #MoveBaseSimple/Goal:
        - factory: mqtt_bridge.bridge:RosToMqttBridge
          msg_type: geometry_msgs.msg:PoseStamped 
          topic_from: /move_base_simple/goal
          topic_to: ~/fromGoal
        - factory: mqtt_bridge.bridge:MqttToRosBridge
          msg_type: geometry_msgs.msg:PoseStamped 
          topic_from: ~/toGoal
          topic_to: /move_base_simple/goal
          
          #/move_base/status Messages:
        - factory: mqtt_bridge.bridge:RosToMqttBridge
          msg_type: actionlib_msgs.msg:GoalStatusArray 
          topic_from: /move_base/status
          topic_to: ~/fromStatus


